# STAT301 2025W2 Group Final Report
## Group 17 I ♥ STAT301
Group members: Niall Calvert, Oliver Hsueh, Karen Li, Bryan Liao

In [9]:
# Load libraries
library(plyr); library(dplyr)
library(gridExtra)

library(MASS)
library(broom)
library(tidymodels)
library(repr)
library(mltools)
library(leaps)
library(modelr)

library(rsample)
library(glmnet)
library(tidyverse)

Loading required package: Matrix


Attaching package: ‘Matrix’


The following objects are masked from ‘package:tidyr’:

    expand, pack, unpack


Loaded glmnet 4.1-8

## (2) Introduction:

Our data comes from the `hotel_bookings` dataset on "https://vincentarelbundock.github.io/Rdatasets/articles/data.html". The data was collected from July 1st, 2015, to August 31st, 2017, from two hotels in Portugal: a resort hotel in Algarve and a city hotel in Lisbon. All bookings were considered, including those that were cancelled. For privacy, all elements concerning hotel or customer identification were deleted. We see various covariates including the time of arrival, the length of stay, chosen meal plan, average daily rate, among others.

The question we want to answer is: what are the primary factors associated with whether a guest cancels a booking or not? 
This question focuses on an inference, trying to find whether the added variables significantly improve the model. The response variable would be is_cancelled, and the linear regression model would model the response as the log odds that is_cancelled = 1, since we would be running a logistic regression since is_canceled is a binary variable. 


We believe the most relevant variables could be lead_time, deposit_type, customer_type, previous_cancellations, and market_segment. Although the dataset contains many variables, only a few relevant ones would be most relevant to the analysis. These variables are associated with the behaviour of the guest booking or cancelling their reservation. We are interested in seeing if the data supports our hypothesis.

Other variables could be included as control variables. For example, adults, children, babies, arrival date, hotel could reduce confounding variables and improve the model fit.

Citation: Antonio, N., de Almeida, A., & Nunes, L (2019). Hotel booking demand datasets. *Data in Brief, Volume 22,* 41-49.

## (3) Methods & Results:

### Data cleaning

In [2]:
# Load the data
hotel_bookings <- read_csv("https://vincentarelbundock.github.io/Rdatasets/csv/bayesrules/hotel_bookings.csv")
head(hotel_bookings)

Rows: 1000 Columns: 33
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (13): hotel, arrival_date_month, meal, country, market_segment, distrib...
dbl  (19): rownames, is_canceled, lead_time, arrival_date_year, arrival_date...
date  (1): reservation_status_date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  rownames hotel        is_canceled lead_time arrival_date_year
1 1        City Hotel   1             1       2015
2 2        Resort Hotel 1            19       2016
3 3        Resort Hotel 0             9       2017
4 4        Resort Hotel 0           110       2016
5 5        City Hotel   0           329       2017
6 6        Resort Hotel 0           212       2017
  arrival_date_month arrival_date_week_number arrival_date_day_of_month
1 September          40                       30
2 March              12                       19
3 August             31                        1
4 November           46                       11
5 July               30                       27
6 August             35                       31
  stays_in_weekend_nights stays_in_week_nights ⋯ deposit_type agent company
1 0                       2                    ⋯ Non Refund   50    NULL
2 2                       4                    ⋯ No Deposit   240   NULL
3 0                       4                    ⋯ No Deposit   241   NULL
4 0                       1                    ⋯ No Deposit   314   NULL
5 0                       2                    ⋯ No Deposit   9     NULL
6 2                       8                    ⋯ No Deposit   143   NULL
  days_in_waiting_list customer_type average_daily_rate
1 0                    Transient      98.10
2 0                    Transient      70.17
3 0                    Transient     193.40
4 0                    Transient      36.24
5 0                    Transient      89.10
6 0                    Transient      89.75
  required_car_parking_spaces total_of_special_requests reservation_status
1 0                           0                         Canceled
2 0                           1                         Canceled
3 0                           1                         Check-Out
4 1                           0                         Check-Out
5 0                           1                         Check-Out
6 0                           0                         Check-Out
  reservation_status_date
1 2015-09-29
2 2016-03-02
3 2017-08-05
4 2016-11-12
5 2017-07-29
6 2017-09-10

Just from examining the data, we see that we have 1000 observations (rows), with 33 columns, 32 of which are variables (not counting `rownames`). Let's see what data types we have for each column:

In [10]:
data.frame(variable_type = sapply(hotel_bookings, class))

                               variable_type
rownames                       numeric
hotel                          character
is_canceled                    numeric
lead_time                      numeric
arrival_date_year              numeric
arrival_date_month             character
arrival_date_week_number       numeric
arrival_date_day_of_month      numeric
stays_in_weekend_nights        numeric
stays_in_week_nights           numeric
adults                         numeric
children                       numeric
babies                         numeric
meal                           character
country                        character
market_segment                 character
distribution_channel           character
is_repeated_guest              numeric
previous_cancellations         numeric
previous_bookings_not_canceled numeric
reserved_room_type             character
assigned_room_type             character
booking_changes                numeric
deposit_type                   character
agent                          character
company                        character
days_in_waiting_list           numeric
customer_type                  character
average_daily_rate             numeric
required_car_parking_spaces    numeric
total_of_special_requests      numeric
reservation_status             character
reservation_status_date        Date

We need to replace "NULL" with NA in applicable variables, such as in `company` and `agent`, so that we can examine for missing values more easily.

In [3]:
# fix null values

hotel_bookings$meal <- revalue(hotel_bookings$meal, c("Undefined"=NA))
hotel_bookings$company <- revalue(hotel_bookings$company, c("NULL"=NA))
hotel_bookings$agent <- revalue(hotel_bookings$agent, c("NULL"=NA))
head(hotel_bookings)

  rownames hotel        is_canceled lead_time arrival_date_year
1 1        City Hotel   1             1       2015
2 2        Resort Hotel 1            19       2016
3 3        Resort Hotel 0             9       2017
4 4        Resort Hotel 0           110       2016
5 5        City Hotel   0           329       2017
6 6        Resort Hotel 0           212       2017
  arrival_date_month arrival_date_week_number arrival_date_day_of_month
1 September          40                       30
2 March              12                       19
3 August             31                        1
4 November           46                       11
5 July               30                       27
6 August             35                       31
  stays_in_weekend_nights stays_in_week_nights ⋯ deposit_type agent company
1 0                       2                    ⋯ Non Refund   50    NA
2 2                       4                    ⋯ No Deposit   240   NA
3 0                       4                    ⋯ No Deposit   241   NA
4 0                       1                    ⋯ No Deposit   314   NA
5 0                       2                    ⋯ No Deposit   9     NA
6 2                       8                    ⋯ No Deposit   143   NA
  days_in_waiting_list customer_type average_daily_rate
1 0                    Transient      98.10
2 0                    Transient      70.17
3 0                    Transient     193.40
4 0                    Transient      36.24
5 0                    Transient      89.10
6 0                    Transient      89.75
  required_car_parking_spaces total_of_special_requests reservation_status
1 0                           0                         Canceled
2 0                           1                         Canceled
3 0                           1                         Check-Out
4 1                           0                         Check-Out
5 0                           1                         Check-Out
6 0                           0                         Check-Out
  reservation_status_date
1 2015-09-29
2 2016-03-02
3 2017-08-05
4 2016-11-12
5 2017-07-29
6 2017-09-10

Let's examine for any class imbalances:

In [11]:
categorical_cols <- c("hotel", "arrival_date_month", "meal", "country", "market_segment", "distribution_channel", 
                      "reserved_room_type", "assigned_room_type", "deposit_type", "customer_type", "reservation_status", "is_canceled")


for (c in categorical_cols) {
    print(table(hotel_bookings[c]))
}

hotel
  City Hotel Resort Hotel
         642          358
arrival_date_month
    April    August  December  February   January      July      June     March
       88       115        75        68        45       111        90        65
      May  November   October September
      126        50        91        76
meal
 BB  FB  HB  SC
761   9 134  87
country
 AGO  ARG  ARM  AUS  AUT  BEL  BGR  BRA  CAF  CHE  CHN   CN  DEU  DNK  DZA  EGY
   1    1    1    5   11   21    1   20    1   18    5   11   66    3    1    1
 ESP  FIN  FRA  GBR  GIB  GRC  HRV  HUN  IND  IRL  ISL  ISR  ITA  KIR  KOR  LBY
  78    5   76  125    1    1    1    2    2   36    1    6   31    1    2    1
 LUX  LVA  MAR  MEX  MOZ  NLD  NOR NULL  NZL  PER  PHL  POL  PRT  ROU  RUS  SGP
   3    1    2    1    1   18    5    2    2    1    1    6  372    2    2    1
 SWE  TUR  TWN  UKR  USA
  10    8    1    1   24
market_segment
Complementary     Corporate        Direct        Groups Offline TA/TO
            6            41           100           163           209
    Online TA
          481
distribution_channel
Corporate    Direct       GDS     TA/TO
       46       121         2       831
reserved_room_type
  A   B   C   D   E   F   G   H
722  10   4 158  59  24  11  12
assigned_room_type
  A   B   C   D   E   F   G   H   I   K
620  24  19 204  69  27  16  16   3   2
deposit_type
No Deposit Non Refund Refundable
       881        116          3
customer_type
       Contract           Group       Transient Transient-Party
             28               4             742             226
reservation_status
 Canceled Check-Out   No-Show
      357       634         9
is_canceled
  0   1
634 366

We see some examples of class imbalance in these categorical variables:
- City hotels make up 64.2% of the observations in the `hotel` category
- 76.1% of `meal`s are 'BB', or 'Bed & Breakfast'
- In `country`, we see that guests from Portugal and Great Britain make up 37.2% and 12.5%, respectively
- In `distribution_channel`, 'TA/TO' makes up 83.1% of values
- 'A' is the most common room type in both `reserved_room_type` and `assigned_room_type`, making up 72.2% and 62% of values respectively
- 'No Deposit' makes up 88.1% of values in `deposit_type`
- 'Transient' makes up 74.2% of values in `customer_type`
- 'Check-Out' makes up 63.4% of values `reservation_status`

We need to also be mindful of the class imbalance in our target variable, `is_canceled`.

### (3c.) Methods Plan

In [4]:
# --- Data preparation ---

# Remove outcome-leaking and non-informative variables
hotel_model <- hotel_bookings |>
  dplyr::select(-rownames,                  # not used in analysis
         -reservation_status,        # directly encodes cancellation
         -reservation_status_date,   # same issue
         -arrival_date_week_number,  # redundant with month
         -arrival_date_day_of_month, 
         -agent,                     # contains too much classes, which  #
         -company,                   # leads to tons of dummy variables  #
         -country) |>                # that generate noises              #
  mutate(is_canceled = as.numeric(as.character(is_canceled))) |>
  drop_na()   # LASSO requires complete cases

# Set seed for reproducibility
set.seed(42)

# Stratified split — 80% train, 20% test
# strata ensures is_canceled proportion is preserved in both sets
split <- initial_split(hotel_model, prop = 0.8, strata = is_canceled)
hotel_train <- training(split)
hotel_test <- testing(split)

# Build model matrix (converts factors to dummies automatically)
model_X_train <- model.matrix(is_canceled ~ . - 1, data = hotel_train)
model_Y_train <- hotel_train$is_canceled

# Build model matrix for testing
model_X_test <- model.matrix(is_canceled ~ . - 1, data = hotel_test)
model_Y_test <- hotel_test$is_canceled

In [5]:
# Step 1: LASSO on training set only
set.seed(52)
lasso_fit <- cv.glmnet(model_X_train, 
                         model_Y_train, 
                         family = "binomial", 
                         type.measure = "auc", # auc is used because there is a class imbalance in is_canceled
                         alpha = 1,
                         nfolds = 3)

best_lambda <- lasso_fit$lambda.1se  # used 1se instead of lambda.min for better interpretability

# Step 2: Extract selected variables from training LASSO
lasso_coefs   <- coef(lasso_fit, s = best_lambda)
selected_vars <- rownames(lasso_coefs)[which(lasso_coefs[, 1] != 0)]
selected_vars <- selected_vars[selected_vars != "(Intercept)"]

cat("Variables selected by LASSO:", length(selected_vars), "\n")  # shows the number of variables that are selected using LASSO
lasso_coefs  # shows the variables that are selected using LASSO
lasso_fit

Variables selected by LASSO: 19

61 x 1 sparse Matrix of class "dgCMatrix"
                                         s1
(Intercept)                    -2.228118329
hotelCity Hotel                 0.029159404
hotelResort Hotel              -0.000614516
lead_time                       0.002650019
arrival_date_year               .
arrival_date_monthAugust        .
arrival_date_monthDecember      .
arrival_date_monthFebruary      .
arrival_date_monthJanuary       .
arrival_date_monthJuly          .
arrival_date_monthJune          0.096833354
arrival_date_monthMarch         .
arrival_date_monthMay           .
arrival_date_monthNovember      .
arrival_date_monthOctober       0.035927177
arrival_date_monthSeptember     .
stays_in_weekend_nights         .
stays_in_week_nights            .
adults                          0.379974128
children                        0.148407025
babies                          .
mealFB                          .
mealHB                         -0.214704080
mealSC                          .
market_segmentCorporate         .
market_segmentDirect           -0.035916137
market_segmentGroups            .
market_segmentOffline TA/TO    -0.092236296
market_segmentOnline TA         0.928758018
distribution_channelDirect     -0.064094842
distribution_channelGDS        -0.149170292
distribution_channelTA/TO       .
is_repeated_guest               .
previous_cancellations          .
previous_bookings_not_canceled  .
reserved_room_typeB             .
reserved_room_typeC             .
reserved_room_typeD             .
reserved_room_typeE             .
reserved_room_typeF             .
reserved_room_typeG             .
reserved_room_typeH             .
assigned_room_typeB            -0.136027133
assigned_room_typeC             .
assigned_room_typeD             .
assigned_room_typeE             .
assigned_room_typeF             .
assigned_room_typeG             .
assigned_room_typeH             .
assigned_room_typeI             .
assigned_room_typeK             .
booking_changes                -0.511170268
deposit_typeNon Refund          3.807146343
deposit_typeRefundable          .
days_in_waiting_list            .
customer_typeGroup              .
customer_typeTransient          .
customer_typeTransient-Party    .
average_daily_rate              0.004485118
required_car_parking_spaces    -1.902910632
total_of_special_requests      -0.788598906

Call:  cv.glmnet(x = model_X_train, y = model_Y_train, type.measure = "auc",      nfolds = 3, family = "binomial", alpha = 1)

Measure: AUC

      Lambda Index Measure      SE Nonzero
min 0.000044    93  0.8615 0.01733      60
1se 0.015538    30  0.8444 0.01180      19

In [6]:
# Step 3: Post-LASSO logistic regression on training set
# hotel_train_postlasso             <- as.data.frame(model_X_train[, selected_vars])
# hotel_train_postlasso$is_canceled <- as.numeric(model_Y_train)

# postlasso_fit <- glm(is_canceled ~ .,
#                      data   = hotel_train_postlasso,
#                      family = "binomial")

# summary(postlasso_fit)